MeeloWebAdmin/Controllers/TenantOnboardingController.cs
using Com.Meelo.CoreLib;
using MeeloWebAdmin.Helper;
using Microsoft.Azure.ActiveDirectory.GraphClient;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MeeloWebAdmin.Controllers
{
    [Authorize]
    public class TenantOnboardingController : Controller
    {
        Organization Organization;
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
                ViewBag.Success =Convert.ToBoolean(TempData["Success"]);
            }
            if (TempData["SuccessRecords"] != null)
            {
                ViewBag.SuccessRecords = TempData["SuccessRecords"].ToString();
                ViewBag.FailureRecords = TempData["FailureRecords"].ToString();
            }
            ActiveDirectoryClient client = AuthenticationHelper.GetActiveDirectoryClientAsApplication();
            //////////////Azure Functions//////////////////
            //string apiUrl = "https://meelofunctionapp.azurewebsites.net/api/ProfilePhotoAPICSharp";//?graphToken="+AuthenticationHelper.TokenForApplication;

            //using (System.Net.Http.HttpClient Httpclient = new System.Net.Http.HttpClient())
            //{
            //    Httpclient.BaseAddress = new Uri(apiUrl);
            //    Httpclient.DefaultRequestHeaders.Accept.Clear();
            //    Httpclient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //    Httpclient.DefaultRequestHeaders.Authorization =
            //        new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", AuthenticationHelper.TokenForApplication);
            //    System.Net.Http.HttpResponseMessage response = Httpclient.GetAsync(apiUrl).Result;
            //    var content = response.Content.ReadAsStringAsync();
            //    if (response.IsSuccessStatusCode)
            //    {
            //        var data = response.Content.ReadAsStringAsync().Result;
            //        var table = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Data.DataTable>(data);

            //    }
            //}
                ///////////////Azure Functions ends here//////////
                GraphApiHelper helper = new GraphApiHelper();
            ITenantDetail Tenant = helper.GetTenantDetails(client);
            Organization = new Organization
            {
                TenantId = Tenant.ObjectId,
                FriendlyName = Tenant.DisplayName,
                CorporateName = Tenant.DisplayName,
                Address = new Address
                {
                    Street = Tenant.Street,
                    City = Tenant.City,
                    State = Tenant.State,
                    Country = Tenant.Country,
                    PostalCode = Tenant.PostalCode,
                },
                OrgContact = new Com.Meelo.CoreLib.User
                {
                    Id = 0,
                    BusinessPhones = new List<string> { Tenant.TelephoneNumber },
                    Mail = Tenant.TechnicalNotificationMails.FirstOrDefault()
                },
                MeeloLicense = new MeeloLicense { }
            };
            ViewBag.Country = Countries.CountryList;
            return View(Organization);
        }
        [HttpPost]
        public JsonResult AddOrganizationBuilding(Organization Org)
        {
            if (Org.Address!=null && Org.Address.GpsLocation.Lat == null)
                Org.Address.GpsLocation.Lat = Org.Address.GpsLocation.Long = 0;
                var OrgOutput = new OrganizationController().Add(Org);

                Building Bld = new Building();
                Bld.Address = Org.Address;
                Bld.Address.GpsLocation = Org.Address.GpsLocation;
                Bld.BuildingName = Org.CorporateName + " Building";
                var BuildingOutput = new BuildingController().Add(Bld);
            
            return OrgOutput;
        }
    }
}

MeeloWebAdmin/Controllers/UserProfileController.cs
using Com.Meelo.BusinessServices.UserProfile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MeeloWebAdmin.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        IUserProfileService iUserProfileService;
        public ActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> UsersList(int jtStartIndex, int jtPageSize, string jtSorting = null, string name = "")
        {
            string TenantId = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
            try
            {
                iUserProfileService = new UserProfileService();
                var users = await iUserProfileService.GetUsers(TenantId);

                return Json(new { Result = "OK", Records = users, TotalRecordCount = users.Count() });
            }

            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

MeeloWebAdmin/Views/TenantOnboarding/Index.cshtml
@model Com.Meelo.CoreLib.Organization
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/modern")
@section Menu{
    <div class="links span8">
        @*@Html.ActionLink("Organization", "Index", "Organization")
            @Html.ActionLink("Users", "Index", "UserProfile")
            @Html.ActionLink("Workspace", "Index", "Workspace")*@
        @Html.ActionLink("Logout", "SignOut", "Account", null, new { @class = "btn btn-default" })
    </div>

}
    <div class="col-md-12">

        @if (ViewBag.Success == false)
        {
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-exclamation-circle padding5px"></i>@Html.Raw(ViewBag.Message)
            @if (ViewBag.SuccessRecords != null)
            {
        <br /><p>@Html.Raw(ViewBag.SuccessRecords) Workspaces Added</p>
        <p>@Html.Raw(ViewBag.FailureRecords) Failed</p>
            }

        </div>
        }
        else if (ViewBag.Success == true)
        {
        <div class="alert alert-success" role="alert">
            <i class="fa fa-check padding5px"></i>@Html.Raw(ViewBag.Message)
            @if (ViewBag.SuccessRecords != null)
    {
        <p>@Html.Raw(ViewBag.SuccessRecords) Workspaces Added Successfully</p>
        <p>@Html.Raw(ViewBag.FailureRecords) Failed</p>
}
        </div>
        }
        <div class="alert alert-danger" role="alert" style="display:none">
            <i class="fa fa-exclamation-circle padding5px"></i><strong> Sorry, an error has occurred</strong><br /><p>Unfortunately an error has occurred during the processing of your page request. We apologize for the inconvenience, Please refresh the page or try again later.</p>
        </div>
        <div class="alert alert-success" role="alert" style="display:none">

        </div>
        <div class="col-md-2"></div>
        <div class="col-md-8">

            <div role="tabpanel">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" id="OrgDetails" class="active"><a href="#tab0" style="margin-left:0px" role="tab" data-toggle="tab">Tenant Organization Details <i class="fa"></i></a></li>
                    <li role="presentation" class="disabled" id="SetupWorkspace"><a href="#tab1">Setting up Workspaces<i class="fa"></i></a></li>
                    @*<li role="presentation" id="professional"><a href="#tab2" role="tab" data-toggle="tab">Import Workspaces from O365<i class="fa"></i></a></li>*@
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active fade in" id="tab0">
                        @using (Ajax.BeginForm("AddOrganizationBuilding", "TenantOnboarding", new AjaxOptions { OnSuccess = "AddOrgSuccess", OnFailure = "AddOrgFailure", LoadingElementId = "progress" }))
                    {
                        Html.RenderPartial("../Organization/OrganizationPartialView", Model);
                    }
                    </div>
                    <div role="tabpanel" class="tab-pane  fade in" id="tab1">
                        @{Html.RenderPartial("../Workspace/WorkspaceSetupPartialView");}
                    </div>
                    @*<div role="tabpanel" class="tab-pane  fade in" id="tab2">
                        @{Html.RenderPartial("../Workspace/WorkspaceImportWizardView");}
                    </div>*@

                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
@*<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyBB4Z4NidYY8AgdXGVGR0d1hwa-kf9IPJU&libraries=places"></script>*@
<script>
    $(document).ready(function () {
        if (document.location.hash === "#tab0") {
            $('#OrgDetails').find('a').trigger('click');
        }
        else if (document.location.hash === "#tab1") {
            $('#SetupWorkspace>a').attr('data-toggle', 'tab');
            $('#SetupWorkspace').find('a').trigger('click');
        }
    });
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        event.preventDefault();
        if (validate("CorporateName,Address_Street,Address_City,Address_State,Address_PostalCode,Address_Country,OrgContact_Mail") == false) {
            evt.preventDefault();
        }

        else if (validate_email("OrgContact_Mail") == false) {
            evt.preventDefault();
        }
    });
    $('#btnSubmit').click(function (evt) {

        if (validate("CorporateName,Address_Street,Address_City,Address_State,Address_PostalCode,Address_Country,OrgContact_Mail") == false) {
            evt.preventDefault();
        }

        else if (validate_email("OrgContact_Mail") == false) {
            evt.preventDefault();
        }


    });
    function validate(field) {
        var fields = field.split(',');
        var Isvalid = true;
        for (var i = 0; i < fields.length; i++) {
            var tabPane = $("#" + fields[i]).parent().parent().parent().parent().parent().parent();
            var tabId = tabPane.attr('id');
            if ($("#" + fields[i]).val().length == 0 || $("#" + fields[i]).val() == "" || $("#" + fields[i]).val() == " " || $("#" + fields[i]).val() == "None" || $("#" + fields[i]).val() == "0") {
                $("." + fields[i] + "-validation-valid").show();
                Isvalid = false;
                $("#" + fields[i]).parent().parent().addClass("has-error");
                $("#" + fields[i]).focus();

                $('a[href="#' + tabId + '"][data-toggle="tab"]')
                    .parent()
                    .find('i')
                    .removeClass('fa-check')
                    .addClass('fa-times');
                $('a[href="#' + tabId + '"][data-toggle="tab"]').trigger('click');
            }
            else {
                $("#" + fields[i]).parent().parent().removeClass("has-error");
                $('a[href="#' + tabId + '"][data-toggle="tab"]')
                    .parent()
                    .find('i')
                    .removeClass('fa-times')
                    .addClass('fa-check');
                $("." + fields[i] + "-validation-valid").hide();
            }
        }
        return Isvalid;
    }
    function validate_email(field) {
        var pattern = /^([a-zA-Z0-9_+\-\.]+)@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
        var tabPane = $("#" + field).parent().parent().parent().parent().parent().parent();
        var tabId = tabPane.attr('id');
        if (pattern.test($("#" + field).val()) == true) {
            $("#" + field).parent().parent().removeClass("has-error");
            $('a[href="#' + tabId + '"][data-toggle="tab"]')
                .parent()
                .find('i')
                .removeClass('fa-times')
                .addClass('fa-check');
            $("." + field + "-validation-valid").hide();
            return true;
        } else {
            $("." + field + "-validation-valid").show()
            $("." + field + "-validation-valid").html("Please enter valid email");
            $("#" + field).parent().parent().addClass("has-error");
            $("#" + field).focus();

            $('a[href="#' + tabId + '"][data-toggle="tab"]')
                .parent()
                .find('i')
                .removeClass('fa-check')
                .addClass('fa-times');
            $('a[href="#' + tabId + '"][data-toggle="tab"]').trigger('click');
            return false;
        }
    }

</script>