MeeloWebAdmin/Controllers/BuildingController.cs
using Com.Meelo.BusinessServices.Building;
using Com.Meelo.CoreLib;
using Com.Meelo.CoreLib.ViewModel;
using ExcelDataReader;
using MeeloWebAdmin.Helper;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MeeloWebAdmin.Controllers
{
    [Authorize]
    public class BuildingController : Controller
    {
        IBuildingService iBuildingServiceObj;
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult Add(Building BuildingObj)
        {
            Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
            if (Org != null)
            {
                iBuildingServiceObj = new BuildingService();
                AddBuildingInput Input = new AddBuildingInput();
                Input.building = BuildingObj;
                Input.OrgId = Input.building.OrgId = Org.OrgId;
                var Output = iBuildingServiceObj.AddBuilding(Input).Result;

                return Json(new { Result = "OK", Record = Output.building });
            }
            return Json(new { Result = "Failed", Record = 0 });

        }
        public JsonResult Update(Building BuildingObj)
        {
            Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
            if (Org != null)
            {
                iBuildingServiceObj = new BuildingService();
                AddBuildingInput Input = new AddBuildingInput();
                Input.building = BuildingObj;
                Input.OrgId = Input.building.OrgId = Org.OrgId;
                var Output = iBuildingServiceObj.UpdateBuilding(Input).Result;

                return Json(new { Result = "OK", Record = Output.building });
            }
            return Json(new { Result = "Failed", Record = 0 });

        }
        public async Task<JsonResult> BuildingList(int jtStartIndex, int jtPageSize, string jtSorting = null, string FilterbyBuilding = null)
        {
            Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
            iBuildingServiceObj = new BuildingService();
            var Output = await iBuildingServiceObj.GetBuilding(Org.OrgId, jtStartIndex, jtPageSize, jtSorting, FilterbyBuilding);
            //if (Buildings == null)
            //    Buildings = new BuildingOutput { building = new Building {Address=new Address {GpsLocation=new GpsLocation() } } };
            return Json(new { Result = "OK", Records = Output.buildings, TotalRecordCount = Output.Count });//Workspaces.Count() });
        }
        public JsonResult GetCountries()
        {
            try
            {
                List<OptionsViewModel> Options = new List<OptionsViewModel>();
                foreach(SelectListItem items in Countries.CountryList)
                {
                    OptionsViewModel Option = new OptionsViewModel();
                    Option.DisplayText = items.Text;
                    Option.Value = items.Value;
                    Options.Add(Option);
                }
                return Json(new { Result = "OK", Options = Options });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
        //public PartialViewResult WorkspaceSetting(Int64 WorkspaceId)
        //{
        //    string tenantID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
        //    iBuildingServiceObj = new BuildingService();
        //    BuildingInput Input = new BuildingInput();
        //    Input.Building.Id = WorkspaceId;
        //    var Output = iBuildingServiceObj.GetBuildingsById(Input).Result;
        //    return PartialView("WorkspacePartialView", Output);
        //}
        //public ActionResult Upload(HttpPostedFileBase upload)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        if (upload != null && upload.ContentLength > 0)
        //        {
        //            Stream stream = upload.InputStream;
        //            IExcelDataReader reader = null;
        //            if (upload.FileName.EndsWith(".xls"))
        //            {
        //                reader = ExcelReaderFactory.CreateBinaryReader(stream);
        //            }
        //            else if (upload.FileName.EndsWith(".xlsx"))
        //            {
        //                reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
        //            }
        //            else
        //            {
        //                ModelState.AddModelError("File", "This file format is not supported");
        //                return View();
        //            }
        //            DataSet DataSetObj = reader.AsDataSet(new ExcelDataSetConfiguration() { ConfigureDataTable = (_) => new ExcelDataTableConfiguration() { UseHeaderRow = true } });
        //            iBuildingServiceObj = new BuildingService();
        //            List<Com.Meelo.CoreLib.Workspace> WorkspaceList = new List<Com.Meelo.CoreLib.Workspace>();
        //            var Result = iWorkspaceServiceObj.AddWorkspace(DataSetObj.Tables[0]).Result;

        //            TempData["Message"] = Result.Message;
        //            TempData["Success"] = Result.IsCallSuccessful;

        //        }
        //    }
        //    return RedirectToAction("Index");
        //}
    }
}

MeeloWebAdmin/Controllers/UserProfileController.cs
using Com.Meelo.BusinessServices.UserProfile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MeeloWebAdmin.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        IUserProfileService iUserProfileService;
        public ActionResult Index()
        {
            return View();
        }
        public async Task<JsonResult> UsersList(int jtStartIndex, int jtPageSize, string jtSorting = null, string name = "")
        {
            string TenantId = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
            try
            {
                iUserProfileService = new UserProfileService();
                var users = await iUserProfileService.GetUsers(TenantId);

                return Json(new { Result = "OK", Records = users, TotalRecordCount = users.Count() });
            }

            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

MeeloWebAdmin/Controllers/WorkspaceController.cs
 using Com.Meelo.BusinessServices.Building;
using Com.Meelo.BusinessServices.Workspace;
using Com.Meelo.CoreLib;
using ExcelDataReader;
using MeeloWebAdmin.Helper;
using Microsoft.Azure.ActiveDirectory.GraphClient;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Configuration;
using Com.Meelo.Utils.Azure.Data.Wrappers;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage;
using Microsoft.Azure.ActiveDirectory.GraphClient.Extensions;

namespace MeeloWebAdmin.Controllers
{
    [Authorize]
    public class WorkspaceController : Controller
    {
        IWorkspaceService iWorkspaceServiceObj;
        IBuildingService iBuildingService;
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
                ViewBag.Success = Convert.ToBoolean(TempData["Success"]);
            }
            if (TempData["SuccessRecords"] != null)
            {
                ViewBag.SuccessRecords = TempData["SuccessRecords"].ToString();
                ViewBag.FailureRecords = TempData["FailureRecords"].ToString();
            }


            return View();
        }
        
        public async Task<JsonResult> WorkspaceList(int jtStartIndex, int jtPageSize, string jtSorting = null, string name = "")
        {
            Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
            iWorkspaceServiceObj = new WorkspaceService();
            var Output = await iWorkspaceServiceObj.GetWorkspacesList(Org.OrgId,jtStartIndex, jtPageSize, jtSorting,name);
            return Json(new { Result = "OK", Records = Output.WorkspaceList, TotalRecordCount = Output.Count });//Workspaces.Count() });
        }
       
        public ActionResult Add(long? WorkspaceId=0)
        {
            if (TempData["Message"] != null)
            {
                ViewBag.Message = TempData["Message"].ToString();
                ViewBag.Success = Convert.ToBoolean(TempData["Success"]);
            }
            long WsId = WorkspaceId??0;
            Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
            Workspace ws = new Workspace();
            ws.Id = WsId;
            WorkspaceOutput Output = new WorkspaceOutput();

            if (WorkspaceId > 0)
            {
                WorkspaceInput Input = new WorkspaceInput();
                Input.Workspace = ws;
                Input.Workspace.Id = WsId;
                Input.Workspace.OrgId = Input.OrgId = Org.OrgId;
                iWorkspaceServiceObj = new WorkspaceService();
                Output = iWorkspaceServiceObj.GetWorkspacesById(Input).Result;
                ws = Output.WorkspaceList.FirstOrDefault();
            }
            else
            {
                ws.LastRenovated = DateTime.UtcNow;
                ws.Address = new Address();
            }
            iBuildingService = new BuildingService();
            var BuildingOutput = iBuildingService.GetBuilding(Org.OrgId, null).Result;
            BuildingOutput.buildings.Insert(0, new Building { BuildingName = "--Select Building--", Id = 0 });
            ViewBag.Buildings =BuildingOutput.buildings; //new SelectList(BuildingOutput.buildings, "Id", "BuildingName", ws.Building.Id); 
            ViewBag.Country= Countries.CountryList;
            if(ws.Building==null)
            ws.Building = new Building();
            return View(ws);
        }
        public ActionResult AddUpdate(Workspace WorkspaceObj, HttpPostedFileBase photo)
        {
            AddWorkspaceOutput AddOutput = new AddWorkspaceOutput();
            bool IsUpdate = false; ;
            try
            {
                Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
                //var blobStorageConnectionString = ConfigurationManager.AppSettings["BlobStorageConnectionString"];

                AddWorkspaceInput WorkspaceInput = new AddWorkspaceInput();
                WorkspaceInput.WorkspaceList = new List<Workspace> { WorkspaceObj };
                iWorkspaceServiceObj = new WorkspaceService();
                WorkspaceObj.LastUpdated = DateTime.UtcNow;
                WorkspaceObj.NextReservationStartTime = DateTime.UtcNow;
                WorkspaceObj.NextReservationEndTime = DateTime.UtcNow;
                WorkspaceObj.OrgId = Org.OrgId;
               
                if (WorkspaceObj.Id == 0)
                {
                    //if (WorkspaceObj.Floor == null)
                    //    WorkspaceObj.Floor = new Floor { Name = WorkspaceObj.Address.Floor };
                    WorkspaceObj.Created = DateTime.UtcNow;
                    AddOutput = iWorkspaceServiceObj.AddWorkspace(WorkspaceInput).Result;
                    AddOutput.Message = "Workspace saved successfully";
                    AddOutput.IsCallSuccessful = true;
                }
                else
                {
                    WorkspaceInput.Workspace = WorkspaceObj;
                    AddOutput = iWorkspaceServiceObj.UpdateWorkspace(WorkspaceInput).Result;
                    AddOutput.Message = "Workspace updated successfully";
                    AddOutput.IsCallSuccessful = true;
                    IsUpdate = true;
                }
                if (photo != null && AddOutput!=null)
                {
                    Com.Meelo.Utils.Azure.WABlobStorageHelper blobHelper = new Com.Meelo.Utils.Azure.WABlobStorageHelper("BlobStorageConnectionString");

                    Com.Meelo.Utils.Azure.WABlobStorageHelper cloudStorageAccount = new Com.Meelo.Utils.Azure.WABlobStorageHelper("BlobStorageConnectionString");
                    CloudBlobClient cloudBlobClient = cloudStorageAccount.BlobClient;
                    CloudBlobContainer cloudBlobContainer = blobHelper.GetBlobContainer("org-" + Org.OrgId);
                    cloudBlobContainer.SetPermissions(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
                    string extension = Path.GetExtension(photo.FileName);
                    CloudBlockBlob cloudBlockBlob = cloudBlobContainer.GetBlockBlobReference("workspace-" + AddOutput.Workspace.Id + "/img-1" + extension);
                    cloudBlockBlob.Properties.ContentType = photo.ContentType;
                    cloudBlockBlob.UploadFromStream(photo.InputStream);
                    WorkspaceObj.PhotoLinks = cloudBlockBlob.Uri.ToString();

                    WorkspaceInput.Workspace = WorkspaceObj;
                    AddOutput = iWorkspaceServiceObj.UpdateWorkspace(WorkspaceInput).Result;
                    AddOutput.Message = "Workspace saved successfully";
                    AddOutput.IsCallSuccessful = true;
                }
                
                iBuildingService = new BuildingService();
                var BuildingOutput = iBuildingService.GetBuilding(Org.OrgId, null).Result;
                ViewBag.Buildings = BuildingOutput.buildings;
                ViewBag.Country = Countries.CountryList;
            }
            catch(Exception ex)
            {
                AddOutput.Message = "<strong> Sorry, an error has occurred</strong><br/><p>Unfortunately an error has occurred during the processing of your page request. We apologize for the inconvenience, Please refresh the page or try again later.</p><br/><p>Error description: " + ex.Message + "</p>";
                AddOutput.IsCallSuccessful = false;
            }
            ViewBag.Message = AddOutput.Message;
            ViewBag.Success = AddOutput.IsCallSuccessful;
            if (IsUpdate)
                return View("Add", WorkspaceObj);
            else
            {
                TempData["Message"] = AddOutput.Message;
                TempData["Success"] = AddOutput.IsCallSuccessful;
                return this.RedirectToAction("Add", new { WorkspaceId = 0 });
            }
        }
        public PartialViewResult WorkspaceSetting(Int64 WorkspaceId)
        {
            string tenantID = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;
            Organization Org = System.Web.HttpContext.Current.Session["Organization"] as Organization;
            iWorkspaceServiceObj = new WorkspaceService();
            WorkspaceInput Input = new WorkspaceInput();
            Input.Workspace = new Workspace();
            Input.Workspace.Id = WorkspaceId;
            Input.Workspace.OrgId = Input.OrgId = Org.OrgId;
           var Output= iWorkspaceServiceObj.GetWorkspacesById(Input).Result;
            if (Output.WorkspaceList!=null && Output.WorkspaceList.Count > 0)
                return PartialView("WorkspacePartialView", Output.WorkspaceList[0]);
            else return null;
        }
        public ActionResult Upload(string ReturnUrl, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    Stream stream = upload.InputStream;
                    IExcelDataReader reader = null;
                    if (upload.FileName.EndsWith(".xls"))
                    {
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    }
                    else if (upload.FileName.EndsWith(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else
                    {
                        ModelState.AddModelError("File", "This file format is not supported");

MeeloWebAdmin/Views/Workspace/ExportWorkspaces.cshtml
@{
    ViewBag.Title = "ImportWorkspaces";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/bundles/modern")
@section Menu{
    <div class="links span8">
        @*@Html.ActionLink("Organization", "Index", "Organization")
            @Html.ActionLink("Users", "Index", "UserProfile")
            @Html.ActionLink("Workspace", "Index", "Workspace")*@
        @Html.ActionLink("Logout", "SignOut", "Account", null, new { @class = "btn btn-default" })
    </div>

}
    <div class="col-md-12">
        <div class="alert alert-danger" role="alert" style="display:none">
            <i class="fa fa-exclamation-circle padding5px"></i><strong> Sorry, an error has occurred</strong><br /><p>Unfortunately an error has occurred during the processing of your page request. We apologize for the inconvenience, Please refresh the page or try again later.</p>
        </div>
        <div class="alert alert-success" role="alert" style="display:none">

        </div>
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div role="tabpanel" class="tab-pane  fade in" id="tab2">
                @{Html.RenderPartial("../Workspace/ImportWorkspaceSuccessPartialView");}
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>

MeeloWebAdmin/Views/Workspace/ImportWorkspaceSuccessPartialView.cshtml
<div class="form-horizontal">

        <h2>Congratulations your tenant is setup, you can review and edit room location and use</h2>

        <div class="form-group">
            <div id="progress">
              
            </div>
            @Html.Label("Rooms :", new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                <label id="lblRoomCount" style="padding-top: 7px;"></label>
            </div>
        </div>
    <div class="form-group">
        <div class="col-md-3"></div>
        <div class="col-md-8">
            <label class="control-label" style="text-align:left">
                Your Workspace rooms and equipment are setup
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3"></div>
        <div class="col-md-8">
            @*<input type="submit" value="Click here to review rooms" class="btn btn-primary" />*@
            @Html.ActionLink("Click here to review rooms", "Index", "Workspace", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $.ajax(
            {
                datatype: "json",
                type: "POST",
                url: "ExportWorkspacesfromO365",
                data: JSON,
                success: function (data) {
                    $("#lblRoomCount").html(data.Records.SuccessRecordsCount);
                    if (data.Records.IsCallSuccessful) {
                        $('.alert-success').show();
                        $('.alert-success').html('<p>' + data.Records.Message + '</p>' +'<p>' + data.Records.SuccessRecordsCount + ' Workspaces Added </p>' + '<p>' + data.Records.FailureRecordsCount + ' Failed</p>');
                    }
                    else {
                        $('.alert-danger').show();
                        $('.alert-success').html('<p>' + data.Records.SuccessRecordsCount + ' Workspaces Added </p>' + '<p>' + data.Records.FailureRecordsCount + ' Failed</p>');
                    }
                    $("#progress").hide();
                },
                error: function () { alert("Error"); }
            });
    });
</script>
<style>
    #progress {
        position: fixed;
        top: 0px;
        right: 0px;
        width: 100%;
        height: 100%;
        background-color: #666;
        background-image: url('../Content/img/Spinner.gif');
        background-repeat: no-repeat;
        background-position: center;
        z-index: 10000000;
        opacity: 0.4;
        filter: alpha(opacity=40); /* For IE8 and earlier */
    }
</style>

MeeloWebAdmin/Views/Workspace/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Menu{
    <div class="links span8 menu">
        @Html.ActionLink("Organization", "Index", "Organization")
        @Html.ActionLink("Buildings", "Index", "Building")
        @Html.ActionLink("Workspace", "Index", "Workspace", null, new { @class = "active" })
        @Html.ActionLink("Logout", "SignOut", "Account", null, new { @class = "btn btn-default" })
    </div>

}
    <div class="col-md-12">
        @if (ViewBag.Success == false)
    {
        <div class="alert alert-danger" role="alert">
            <i class="fa fa-exclamation-circle padding5px"></i>@Html.Raw(ViewBag.Message)
            @if (ViewBag.SuccessRecords != null)
        {
            <br /><p>@Html.Raw(ViewBag.SuccessRecords) Workspaces Added</p>
            <p>@Html.Raw(ViewBag.FailureRecords) Failed</p>
    }

        </div>
}
else if (ViewBag.Success == true)
{
        <div class="alert alert-success" role="alert">
            <i class="fa fa-check padding5px"></i>@Html.Raw(ViewBag.Message)
            @if (ViewBag.SuccessRecords != null)
    {
        <p>@Html.Raw(ViewBag.SuccessRecords) Workspaces Added Successfully</p>
        <p>@Html.Raw(ViewBag.FailureRecords) Failed</p>
}
        </div>
}
    </div>
<div class="col-md-12">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2>Workspace</h2>
        <div class="card-box">
            <div class="links span6">
                @Html.ActionLink("Add Workspace", "Add", "Workspace", new { WorkspaceId = 0 }, new { @class = "btn signup blue2" })
                <button type="button" class="btn Rectangle signup blue2" data-toggle="modal" data-target="#myModal">Import</button>
            </div>
            <div id="Workspaces" style="overflow-x:scroll">
            </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
@using (Html.BeginForm("Upload", "Workspace", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.Hidden("ReturnUrl", "Index")
    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Import Workspace</h4>
                    <hr />
                    <p>Select your workspace file to import. We currently support CSV and Excel files.</p>
                </div>
                <div class="modal-body">
                    <input type="file" id="dataFile" name="upload" title="Choose a file to import…" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn Rectangle lightgray" data-dismiss="modal">Cancel</button>
                    <input type="submit" class="btn Rectangle signup blue2" value="Import" />
                </div>
            </div>

        </div>
    </div>
    <div id="SettingModel" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Settings</h4>

                    <hr />
                </div>
                <div class="modal-body">
                    <div id="#SettingContent"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn Rectangle lightgray" data-dismiss="modal">Cancel</button>
                    <input type="submit" class="btn Rectangle signup blue2" value="Save" />
                </div>
            </div>

        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryjt")
@Styles.Render("~/Content/jtable")
<script>
    $(document).ready(function () {
        GeWorkspaceList();
    });
    function GetSetting(WorkspaceId) {
        $.ajax({
            url: "../Workspace/WorkspaceSetting?WorkspaceId=" + WorkspaceId,
            dataType: "html",
            type: "POST",
            contentType: "application/html; charset=utf-8",
            success: function (response) {

                //$('#SettingModel').modal('show');
                //$("#SettingContent").html(response);
                $('#SettingModel .modal-body').html(response);
                $('#SettingModel').on('shown.bs.modal', function (e) {
                    $('#SettingModel .modal-title').html($("#Building_BuildingName").val()+ " Settings");
                })
                $('#SettingModel').modal('show');

            },
            failure: function (response) {
            }
        });
    }
    function GeWorkspaceList() {
        $("#Workspaces").jtable({
            title: '',
            paging: true,
            pageSize: 10,
            sorting: true,
            defaultSorting: 'FirstName ASC',
            actions: {
                listAction: '@Url.Action("../Workspace/WorkspaceList")'
            },
            fields: {
                Id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },

                Address:
                {
                    title: 'Address',
                    width: '23%',
                    display: function (data) {
                        if (data.record.Address.Street != null)
                            return data.record.Address.Street + ' ' + data.record.Address.City + ' ' + data.record.Address.State + ' ' + data.record.Address.Country;
                        else
                            return data.record.Address.City + ' ' + data.record.Address.State + ' ' + data.record.Address.Country;
                    }
                },
                Name: {
                    title: 'Name',
                    width: '20%'
                },
                IsBlocked: {
                    title: 'Status',
                    width: '7%'
                },
                LastUpdated: {
                    title: 'Last Modified',
                     type: 'date',
                    displayFormat: 'yy-mm-dd',
                    width: '20%'
                },
                Actions: {
                    title: 'Status',
                    width: '10%',
                    display: function (data) {

                        return '<a href="Workspace/Add?WorkspaceId=' + data.record.Id +'" >Settings</a>'

                    }
                }
            }
        });


        $('#Workspaces').jtable('load');

    }
</script>

MeeloWebAdmin/Views/Workspace/WorkspaceSetupPartialView.cshtml
<p>You can setup your Meelo workspaces using one of the three options , click on any one for setup</p>
<div class="form-horizontal" style="border-bottom: 1px solid #dddddd; margin-bottom: 10px;">
    <div class="form-group">
        @Html.Label("O", new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @*<button type="button" class="btn btn-primary" onclick="Next()">Import from O365 Tenant</button>*@
            @Html.ActionLink("Export from O365 Tenant", "ExportWorkspaces", "Workspace", null, new { @class = "btn btn-primary" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("O", new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#WorkspaceImport">Import  from excel</button>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("O", new { @class = "control-label col-md-4" })
        <div class="col-md-8">
            @Html.ActionLink("Add Manually", "Add", "Workspace", new { WorkspaceId = 0 }, new { @class = "btn btn btn-primary" })
        </div>
    </div>
    
</div>
<div class="form-group">
    <div class="col-md-offset-9 col-md-10">
        @Html.ActionLink("Finish Setup", "index", "Organization", new { WorkspaceId = 0 }, new { @class = "btn btn btn-info" })
    </div>
</div>
@using (Html.BeginForm("Upload", "Workspace", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    @Html.Hidden("ReturnUrl", "../TenantOnboarding/Index")
    <!-- Modal -->
    <div id="WorkspaceImport" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Import Workspace</h4>
                    <hr />
                    <p>Select your workspace file to import. We currently support CSV and Excel files.</p>
                </div>
                <div class="modal-body">
                    <input type="file" id="dataFile" name="upload" title="Choose a file to import…" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn Rectangle lightgray" data-dismiss="modal">Cancel</button>
                    <input type="submit" class="btn Rectangle signup blue2" value="Import" />
                </div>
            </div>

        </div>
    </div>
    
}